name = "mailfree"
# name = "mail-exhibit"
main = "src/server.js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "TEMP_MAIL_DB"
database_name = "moemail-db" #你的d1数据库名称
database_id = "1cdaab4e-3bef-44d3-82cb-dd0146da0727" # 你的database_id
# 登录会话过期时间（单位：天，默认365天）
# 环境变量
[vars]
# FORWARD_RULES="[{"prefix":"vip","email":"a@example.com"},{"prefix":"*","email":"example@qq.com"}]"
ADMIN_NAME="zzy"
ADMIN_PASSWORD="gdsc90zzy"
GUEST_PASSWORD="guest"
JWT_TOKEN="sdawdadsdaw"
JWT_TOKENGUEST_PASSWORD="sdasdawda"
SESSION_EXPIRE_DAYS="365"
MAIL_DOMAIN="test.domain"
RESEND_API_KEY="gdsc90zzy"



# 静态资源目录（Workers + Assets）
[assets]
directory = "public"
# 显式指定绑定名，确保在 Worker 中通过 env.ASSETS 可用
binding = "ASSETS"


# R2 存储桶绑定（用于保存完整 EML 内容）
[[r2_buckets]]
binding = "MAIL_EML"
bucket_name = "mail-eml"

# wrangler.toml (wrangler v3.88.0^) 日志服务
# [observability.logs]
# enabled = true


